/* eslint-disable no-underscore-dangle */
import {
  Box,
  Dialog,
  Fab,
  useMediaQuery,
  useTheme,
  Typography,
} from "@material-ui/core";
import {
  GridColumns,
  GridRowData,
  GridRenderCellParams,
} from "@mui/x-data-grid";
import { makeStyles } from "@material-ui/core/styles";
import AddIcon from "@material-ui/icons/Add";
import { GeneralButton, IconLabelButton } from "components/Buttons";
import LoadingScreen from "components/LoadingScreen";
import ResponsiveDataGrid from "components/ResponsiveGrid";
import React, { useState } from "react";
import { useQuery } from "react-query";
import gnFetch from "util/gnAxiosClient";
import AccountForm from "../../../components/Form/accountForm";

const useStyles = makeStyles({
  createButton: {
    marginBottom: 12,
  },
  heading: {
    lineHeight: 3,
  },
  fab: {
    margin: "0px",
    top: "auto",
    right: "30px",
    bottom: "30px",
    left: "auto",
    position: "fixed",
  },
});

// Strapi sends role data as a named array for some reason.
interface RoleData {
  roles: Role[];
}

const AccountManagement = () => {
  const [hideForm, setHideForm] = useState(true);
  const [creationMode, setCreationMode] = useState(false);
  const [editUser, setEditUser] = useState(null);

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("xs"));
  const classes = useStyles();

  const allUserData = useQuery<User[]>(
    "get-all-users-account-data",
    async () => (await gnFetch.get("/users/")).data,
    {
      cacheTime: 600,
    }
  );

  // Roles generated by strapi that aren't necessary to be seen on frontend
  const RolesToBeRemoved = ["Authenticated", "Public"];
  const allRoles = useQuery<RoleData>(
    "get-all-genyus-roles",
    async () => (await gnFetch.get("/users-permissions/roles")).data,
    {
      cacheTime: 600,
    }
  );

  const allOrgs = useQuery<Organisation[]>(
    "get-all-organisations",
    async () => (await gnFetch.get("/organisations")).data,
    {
      cacheTime: 600,
    }
  );

  const onEditClick = (user: User) => {
    setEditUser(user);
    setCreationMode(false);
    setHideForm(false);
  };

  const onCreateNewClick = () => {
    setEditUser(null);
    setCreationMode(true);
    setHideForm(false);
  };

  const columns: GridColumns = [
    { field: "username", headerName: "Username", flex: 1 },
    { field: "name", headerName: "Name", flex: 1 },
    { field: "email", headerName: "Email", flex: 1 },
    { field: "organisation", headerName: "Organisation", flex: 1 },
    { field: "accessLevel", headerName: "Access Level", flex: 1 },
    { field: "phone", headerName: "Phone No.", flex: 1 },
    { field: "active", headerName: "Active", flex: 1 },
    {
      field: "edit",
      headerName: "Edit",
      flex: 1,
      renderCell: (params: GridRenderCellParams) => (
        <GeneralButton onClick={() => onEditClick(params.row.actions)}>
          Edit
        </GeneralButton>
      ),
    },
  ];

  const accountRows: GridRowData[] = [];
  if (allUserData.isSuccess) {
    allUserData.data.forEach((user) =>
      accountRows.push({
        id: user.id,
        username: user.username,
        accessLevel: user.role.name,
        active: user.blocked ? "No" : "Yes",
        email: user.email,
        organisation: user.organisation?.name,
        phone: user.phone,
        name: `${user.firstName} ${user.lastName}`,
        actions: user,
      })
    );
  }

  if (!allUserData.isSuccess || !allOrgs.isSuccess || !allUserData.isSuccess)
    return <LoadingScreen />;

  return (
    <>
      <Typography variant="h4" className={classes.heading}>
        Acount Overview
      </Typography>
      {!isMobile && (
        <Box className={classes.createButton}>
          <IconLabelButton
            type="add"
            iconPosition="start"
            onClick={onCreateNewClick}
          >
            CREATE NEW
          </IconLabelButton>
        </Box>
      )}
      {isMobile && (
        <Fab className={classes.fab} color="primary" onClick={onCreateNewClick}>
          <AddIcon />
        </Fab>
      )}

      <ResponsiveDataGrid rows={accountRows} columns={columns} />
      <Dialog open={!hideForm} onClose={() => setHideForm(true)}>
        <AccountForm
          isCreateUser={creationMode}
          userUnderEdit={editUser}
          roles={
            allRoles.isSuccess
              ? allRoles.data.roles.filter(
                  (role) => !RolesToBeRemoved.includes(role.name)
                )
              : []
          }
          organisations={allOrgs.isSuccess ? allOrgs.data : []}
          handleClose={() => setHideForm(true)}
          onSubmitSettled={() =>
            allUserData.refetch().then(() => setHideForm(true))
          }
        />
      </Dialog>
    </>
  );
};

export default AccountManagement;
