version: '3'
services:
  strapi:
    build:
      context: strapi
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./strapi/strapi-app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  mongo:
    build:
      context: mongo
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./mongo/db-data:/data/db

  nextjs:
    ports:
      -  3000:3000
    build:
      context: next
      dockerfile: Dockerfile
    volumes:
      - ./next/app:/usr/src/app

