name: Frontend Pipeline
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed

jobs:
  git-sync:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Sync next to genyusnetwork.devops private repo
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:SWEN90013-2021-GN/GN.git"
          source_branch: "main"
          destination_repo: "git@github.com:genyusnetworkdevops/GN.git"
          destination_branch: "main"
          source_ssh_private_key: ${{ secrets.NEXT_DEPLOY_SOURCE_SECRET }}
          destination_ssh_private_key: ${{ secrets.NEXT_DEPLOY_DESTINATION_SECRET }}
