name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Stack
        run: | 
          docker-compose build --build-arg GDRIVE_PRIVATE_KEY_ID_TEMP="${{ secrets.GDRIVE_PRIVATE_KEY_ID }}" --build-arg GDRIVE_PRIVATE_KEY_TEMP="${{ secrets.GDRIVE_PRIVATE_KEY }}" nextjs
      - name: Start Docker Stack
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up -d --no-recreate
      - name: Install Cypress
        run: |
          cd $GITHUB_WORKSPACE/next
          yarn install --frozen-lockfile
      - name: Run Tests
        run: |
          cd $GITHUB_WORKSPACE/next
          yarn test
      - name: Generate coverage report
        run: |
          cd $GITHUB_WORKSPACE/next
          yarn run coverage
          yarn run coverage-report
