name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Stack
        env:
          GDRIVE_PRIVATE_KEY_ID: ${{ secrets.GDRIVE_PRIVATE_KEY_ID }}
          GDRIVE_PRIVATE_KEY: ${{ secrets.GDRIVE_PRIVATE_KEY }}
        run: |
          echo "$GDRIVE_PRIVATE_KEY_ID"
          cd $GITHUB_WORKSPACE
          docker-compose build --build-arg GDRIVE_PRIVATE_KEY_ID=$GDRIVE_PRIVATE_KEY_ID --build-arg GDRIVE_PRIVATE_KEY=$GDRIVE_PRIVATE_KEY nextjs
      - name: Start Docker Stack
        run: docker-compose up -d --no-recreate
      - name: Install Cypress
        run: |
          cd $GITHUB_WORKSPACE/next
          yarn install --frozen-lockfile
      - name: Run Tests
        run: |
          cd $GITHUB_WORKSPACE/next
          yarn test
      - name: Generate coverage report
        run: |
          cd $GITHUB_WORKSPACE/next
          yarn run coverage
          yarn run coverage-report
